name: Make-build

on:
  - push
  - pull_request

jobs:
  test-make-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build with Gradle
        run: make build 
